### ISSUE TITLE
Rspec｜Rails Tutorial｜7章のエラーを修正する

### ISSUE THREAD

**Issue by yuito-syz** [yuito-syz/portfolio#142]
```bash
% bin/rspec
Running via Spring preloader in process 81129

User
  should be valid
  is invalid with no name
  is invalid with no mail
  is invalid with 51-letter names
  is invalid with 256-letter mails
  is valid with the correct email's format
  is invalid with the wrong email's format
  is invalid with registered email
  is invalid with registered email
  is invalid with no password
  is invalid with 5-letter passwords

Staticpages
  GET /
    returns http success
  GET /help
    returns http success
  GET /about
    returns http success

Users
  POST /users
    adds new user with correct signup information (FAILED - 1)

UsersSignups
Warning: You're using an unsupported version of selenium-webdriver, please upgrade.
Warning: You're using an unsupported version of selenium-webdriver, please upgrade.
  Don't create new data when user submits invalid information
  Create new data when user submits valid information (FAILED - 2)

Failures:

  1) Users POST /users adds new user with correct signup information
     Failure/Error: expect(response).to redirect_to user_path(User.last)
     
       Expected response to be a redirect to <http://www.example.com/users/27> but was a redirect to <http://www.example.com/>.
       Expected "http://www.example.com/users/27" to be === "http://www.example.com/".
     # ./spec/requests/users_request_spec.rb:12:in `block (4 levels) in <main>'
     # ./spec/requests/users_request_spec.rb:7:in `block (3 levels) in <main>'
     # -e:1:in `<main>'

  2) UsersSignups Create new data when user submits valid information
     Got 2 failures from failure aggregation block.
     # ./spec/system/users_signups_spec.rb:25:in `block (2 levels) in <main>'
     # -e:1:in `<main>'

     2.1) Failure/Error: expect(current_path).to eq user_path(User.find_by(email: "user@example.com"))
          
            expected: "/users/28"
                 got: "/"
          
            (compared using ==)
          
          [Screenshot]: /Users/nemuson/Development/rails/portfolio/tmp/screenshots/failures_r_spec_example_groups_users_signups_create_new_data_when_user_submits_valid_information_135.png

          
          # ./spec/system/users_signups_spec.rb:26:in `block (3 levels) in <main>'
          # ./spec/system/users_signups_spec.rb:25:in `block (2 levels) in <main>'

     2.2) Failure/Error: expect(has_css?('.alert-success')).to be_truthy
          
            expected: truthy value
                 got: false
          
          
          [Screenshot]: /Users/nemuson/Development/rails/portfolio/tmp/screenshots/failures_r_spec_example_groups_users_signups_create_new_data_when_user_submits_valid_information_135.png

          
          
          # ./spec/system/users_signups_spec.rb:27:in `block (3 levels) in <main>'
          # ./spec/system/users_signups_spec.rb:25:in `block (2 levels) in <main>'

Finished in 9.5 seconds (files took 0.34769 seconds to load)
17 examples, 2 failures

Failed examples:

rspec ./spec/requests/users_request_spec.rb:6 # Users POST /users adds new user with correct signup information
rspec ./spec/system/users_signups_spec.rb:18 # UsersSignups Create new data when user submits valid information

```

**Comment by yuito-syz** [comment]
expectedとgotの帳尻を合わせる
