### ISSUE TITLE
masterで「heroku run rails c」した際のエラーを直す

### ISSUE THREAD

**Issue by yuito-syz** [yuito-syz/portfolio#27]
/app/app/controllers/posts_controller.rb:2:in `<class:PostsController>': undefined local variable or method `only' for PostsController:Class (NameError)

``$ heroku run rails c
 ›   Warning: heroku update available from 7.54.1 to 7.59.2.
Running rails c on ⬢ rails-portfolio-tyranno22... up, run.7214 (Free)
Traceback (most recent call last):
        62: from /app/bin/rails:9:in `<main>'
        61: from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
        60: from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
        59: from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
        58: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        57: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        56: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        55: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        54: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
        53: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/commands.rb:18:in `<main>'
        52: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/command.rb:46:in `invoke'
        51: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/command/base.rb:69:in `perform'
        50: from /app/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        49: from /app/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        48: from /app/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        47: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/commands/console/console_command.rb:101:in `perform'
        46: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
        45: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/command/actions.rb:28:in `require_environment!'
        44: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/application.rb:339:in `require_environment!'
        43: from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
        42: from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
        41: from /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
        40: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
        39: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        38: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        37: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        36: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        35: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
        34: from /app/config/environment.rb:5:in `<main>'
        33: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/application.rb:363:in `initialize!'
        32: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/initializable.rb:60:in `run_initializers'
        31: from /app/vendor/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
        30: from /app/vendor/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
        29: from /app/vendor/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
        28: from /app/vendor/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:347:in `call'
        27: from /app/vendor/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:347:in `each'
        26: from /app/vendor/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
        25: from /app/vendor/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
        24: from /app/vendor/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        23: from /app/vendor/ruby-2.7.4/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
        22: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        21: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/initializable.rb:32:in `run'
        20: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/initializable.rb:32:in `instance_exec'
        19: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/application/finisher.rb:122:in `block in <module:Finisher>'
        18: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:312:in `eager_load_all'
        17: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:312:in `each'
        16: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:212:in `eager_load'
        15: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:212:in `synchronize'
        14: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:227:in `block in eager_load'
        13: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:18:in `ls'
        12: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
        11: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
        10: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:232:in `block (2 levels) in eager_load'
         9: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:95:in `cget'
         8: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
         7: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:27:in `require'
         6: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
         5: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
         4: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
         3: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
         2: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
         1: from /app/app/controllers/posts_controller.rb:1:in `<main>'
/app/app/controllers/posts_controller.rb:2:in `<class:PostsController>': undefined local variable or method `only' for PostsController:Class (NameError)``

**Comment by yuito-syz** [comment]
/portfolio/app/controllers/posts_controller.rbの

`before_actions :find_post, only[:show, :edit, :update, :destroy]`を
`before_action :find_post, only: [:show, :edit, :update, :destroy]`に直したら

`heroku run rails c`通りました
