### ISSUE TITLE
Rspec

### ISSUE THREAD

**Issue by yuito-syz** [yuito-syz/portfolio#6]
### https://github.com/rspec/rspec-rails
初めにRailsチュートリアルのsample_appのテストを書き直す

[読み物ガイド](https://railstutorial.jp/reading_guide)

[公式ドキュメント](https://relishapp.com/rspec/rspec-rails/docs/directory-structure)

**Comment by yuito-syz** [comment]
【RSpec】Railsチュートリアル第6版　第3章
[https://qiita.com/supyolo888/items/35081ead2cfafb40a995](url)

**Comment by yuito-syz** [comment]
https://qiita.com/sakakinn/items/9c4d6e278cd19867f80f

**Comment by yuito-syz** [comment]
[読み物ガイド](https://railstutorial.jp/reading_guide)

**Comment by yuito-syz** [comment]
[RSpec基礎講座](https://github.com/pepabo/training/blob/master/workshop/rspec/rspec.md)

**Comment by yuito-syz** [comment]
<img width="1440" alt="RSpecの続きはここから" src="https://user-images.githubusercontent.com/57525739/145311122-904b0320-c2f4-4eec-bf3d-88ca2697eed5.png">

**Comment by yuito-syz** [comment]
`spec/requests/static_pages.rb`を作りたい時は、
` rails g rspec:request static`というコマンドを打てば良い

**Comment by yuito-syz** [comment]
[基礎からやり直す Rails RSpec](https://qiita.com/kskinaba/items/38b143e79bdfd44cc42a)

**Comment by yuito-syz** [comment]
[【RSpec】spec/rails_helper.rbを和訳&補足してみた](https://qiita.com/aiandrox/items/7ff4d73416dc15f0cc0f)

**Comment by yuito-syz** [comment]
```
% bin/rspec
Running via Spring preloader in process 31674

An error occurred while loading ./spec/requests/static_pages_spec.rb.
Failure/Error: ActiveRecord::Migration.maintain_test_schema!

Mysql2::Error::ConnectionError:
  Access denied for user 'ENV['PORTFOLIO_DB_USERNAME']'@'localhost' (using password: YES)
# ./spec/rails_helper.rb:28:in `<main>'
# ./spec/requests/static_pages_spec.rb:1:in `<main>'
# -e:1:in `<main>'
No examples found.


Finished in 0.00008 seconds (files took 0.4391 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by yuito-syz** [comment]
[開発環境か本番環境がわかるようになるgem](https://github.com/dtaniwaki/rack-dev-mark)

**Comment by yuito-syz** [comment]
[Ruby on Rails のテストフレームワーク RSpec 事始め
]{https://qiita.com/tatsurou313/items/c923338d2e3c07dfd9ee#request-%E3%83%86%E3%82%B9%E3%83%88%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)

**Comment by yuito-syz** [comment]
#90

**Comment by yuito-syz** [comment]
#90
